config/routes.rb
SampleApp::Application.routes.draw do
  resources :users do
   collection do
    get :tmp
   end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts
  resources :entries
  resources :comments
  resources :articles
  resources :categories
  resources :profiles
  resources :subemails
  resources :contacts
  root 'static_pages#home'
  match '/signup',   to:'users#new',              via:'get'
  match '/signin',   to:'sessions#new',           via:'get'
  match '/signout',  to:'sessions#destroy',       via:'delete'
  match '/help',     to: 'static_pages#help',     via: 'get'
  match '/bbs',      to: 'static_pages#bbs',      via: 'get'
  match '/about',    to: 'static_pages#about',    via: 'get'
  match '/mypage',   to: 'static_pages#mypage',   via: 'get'
  get 'users/token/:uuid' => 'users#token'

end

app/models/article.rb
class Article < ActiveRecord::Base
 validates :title, presence: true
 validates :abstract, presence: true
 validates :content, presence: true, length: { maximum: 140000 }
 default_scope -> { order('created_at DESC') }
 mount_uploader :image, ImageUploader
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
 before_action :signed_in_user, only: [:new, :edit, :update, :destroy]
 before_action :admin_user,     only: [:new, :edit, :update, :destroy]

 def new
  @article = Article.new
 end

 def edit
  @article = Article.find(params[:id])
 end

 def create
  @article = Article.new(article_params)
  if @article.save
   flash[:success] = "Article created!"
   redirect_to @article
   if @article.koukai == 1 && @article.send_mail == 1
    users = User.all
    users.each do |user| 
     PostMailer.post_email(user, @article).deliver
    end
   end
  else
   render 'new'
  end
 end

 def destroy
  @article = Article.find(params[:id])
  @article.destroy
  redirect_to article_path
 end

 def show
  @article = Article.find(params[:id])
  case 
   when @article.content4.present?
    @all_contents = [@article.content, @article.content2, @article.content3, @article.content4]
   when @article.content3.present?
    @all_contents = [@article.content, @article.content2, @article.content3]
   when @article.content2.present?
    @all_contents = [@article.content, @article.content2]
   else
    @all_contents = [@article.content]
  end
  @paginated_content = @all_contents.paginate(page: params[:page], per_page: 1)
 end

 def update
  @article = Article.find(params[:id])
  if @article.update_attributes(article_params)
   flash[:success] = "Article updated!"
   redirect_to @article
   if @article.koukai == 1 && @article.send_mail == 1 
    users = User.all
    users.each do |user| 
     PostMailer.post_email(user, @article).deliver
    end
   end
  else
   render 'edit'
  end
 end

 def index
  @public_articles = Article.where(koukai: 1).paginate(page: params[:page])
  @articles = Article.paginate(page: params[:page])
 end

 
#def category
#  @articles = Article.where(public: 1)
#  @categorized_articles_0 = @articles.where(public: 0).paginate(page: params[:page])
#  @categorized_articles_1 = @articles.where(public: 1).paginate(page: params[:page])
#  @categorized_articles_2 = @articles.where(public: 2).paginate(page: params[:page])
# end 

 private

 def article_params
  params.require(:article).permit(:title, :abstract, :content, :content2, :content3, :content4, :category_id, :koukai, :gentei, :send_mail, :image, :image_cache, :remove_image)
 end

 def admin_user
  redirect_to(root_path) unless current_user.admin?
 end


end

app/views/articles/_form.html.erb
 <%= form_for(@article) do |f| %>
     <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :title %>
      <%= f.text_field :title %>

      <%= f.label :abstract %>
      <%= f.text_area :abstract %>

      <%= f.label :content %>
      <%= f.text_area :content %>

      <%= f.label :category_id %>
      <%= f.select :category_id,
          [['一回生向け', 1], ['Sojin Voice', 2], ['その他', 3]]  %>

      <%= f.label :koukai %>
      <%= f.select :koukai,
          [['下書き', 0], ['公開', 1]]  %>
      
      <%= f.label :gentei %>
      <%= f.select :gentei,
          [['通常公開', 0], ['会員限定', 1]]  %>


      <%= f.submit "Post", class: "btn btn-large btn-primary" %>
    <% end %>

app/views/articles/edit.html.erb
<h3>記事編集</h3>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@article) do |f| %>
     <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :title %>
      <%= f.text_field :title %>

      <%= f.label :abstract %>
      <%= f.text_area :abstract %>

      <%= f.label :content %>
      <%= f.text_area :content %>

      <%= f.label :content2 %>
      <%= f.text_area :content2 %>

      <%= f.label :content3 %>
      <%= f.text_area :content3 %>

      <%= f.label :content4 %>
      <%= f.text_area :content4 %>

      <%= f.label :category_id %>
      <%= f.select :category_id,
          [['一回生向け', 1], ['Sojin Voice', 2], ['その他', 3]]  %>

      <%= f.label :koukai %>
      <%= f.select :koukai,
          [['下書き', 0], ['公開', 1]]  %>

      <%= f.label :gentei %>
      <%= f.select :gentei,
          [['通常公開', 0], ['会員限定', 1]]  %>

      <%= f.label :send_mail, '通知メール' %>
      <%= f.select :send_mail,
          [['送信しない', 0], ['送信する', 1]] %>

    <div class="field">
     <% if @article.image? %>
       <div class="thumbnail">
       <%= image_tag @article.image.url %>
       </div>
      <% end %><br>
       <%= f.label :image %>
       <%= f.file_field :image %>
       <%= f.hidden_field :image_cache %>
      </div> 
      <div class="field">
        <!-- 既存レコード(DBに保存されている)かつ、画像が存在する場合 -->
        <% if @article.persisted? && @article.image? %>
        <label>
         <%= f.check_box :remove_image %>
         画像を削除
         </label>
        <% end %>
      </div>



      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
 </div>
</div>

app/views/articles/index.html.erb
<h1> Articles </h1>

 <div class="users">
   <%= render 'shared/articles' %>
 </div>

app/views/articles/new.html.erb
<h3>記事作成</h3>

<div class="row">
  <div class="span6 offset3">
      <%= form_for(@article) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :title %>
      <%= f.text_field :title %>

      <%= f.label :abstract %>
      <%= f.text_area :abstract %>

      <%= f.label :content %>
      <%= f.text_area :content %>

      <%= f.label :content2 %>
      <%= f.text_area :content2 %>

      <%= f.label :content3 %>
      <%= f.text_area :content3 %>

      <%= f.label :content4 %>
      <%= f.text_area :content4 %>

      <%= f.label :category_id %>
      <%= f.select :category_id,
          [['一回生向け', 1], ['Sojin Voice', 2], ['その他', 3]]  %>

      <%= f.label :koukai %>
      <%= f.select :koukai,
          [['下書き', 0], ['公開', 1]]  %>

      <%= f.label :gentei %>
      <%= f.select :gentei,
          [['通常公開', 0], ['会員限定', 1]]  %>

      <%= f.label :send_mail, '通知メール' %>
      <%= f.select :send_mail,
          [['送信しない', 0], ['送信する', 1]] %>

      <div class="field">
      <% if @article.image? %>
       <div class="thumbnail">
       <%= image_tag @article.image.url %>
       </div>
      <% end %><br>
       <%= f.label :image %>
       <%= f.file_field :image %>
       <%= f.hidden_field :image_cache %>
      </div>
      <div class="field">
        <!-- 既存レコード(DBに保存されている)かつ、画像が存在する場合 -->
        <% if @article.persisted? && @article.image? %>
        <label>
         <%= f.check_box :remove_image %>
         画像を削除
         </label>
        <% end %>
      </div>



      <%= f.submit "Post", class: "btn btn-large btn-primary" %>
    <% end %>
 </div>
</div>

app/views/articles/show.html.erb
<% if @article.koukai == 1 %>
  <% if (@article.gentei == 1) && !signed_in?  %>
   <% session[:return_to] = request.original_url %>
   <h4>こちらはユーザー限定公開記事です。
　 <%= link_to "サインイン", signin_path %>か<%= link_to "ユーザー登録", signup_path %>をしてください。</h4>
  <% else %>
   <h2 class="ttl1"><%= @article.title %></h2>
   <div class="box2">
   <h2 class="abst1"><%= @article.abstract %></h2>
   <% if @article.image? %>
      <div class="thumbnail">
      <%= image_tag @article.image.url %>
      </div>
   <% end %>
   <h22 class="content1">
   <%= simple_format(@paginated_content.first) %>
   </h22>
   <%= will_paginate @paginated_content %>
   <p>
    <% case %>
    <% when @article.category_id == 1 %>
     <%= link_to "#一回生向け", '/categories/1' %>
    <% when @article.category_id == 2 %>
     <%= link_to "#Sojin Voice", '/categories/2' %>
    <% else @article.category_id == 3 %>
     <%= link_to "#その他", '/categories/3' %>
    <% end %>
   </p>
    <% if signed_in? && current_user.admin? %>
     <%= link_to "edit", edit_article_path(params[:id]) %>
     <%= link_to "delete", @article, method: :delete,
                      data: {confirm: "You sure?"} %>
     </div>
    <% end %>
  <% end %>
<% else %>
 <% if signed_in? && current_user.admin? %>
  <h2 class="ttl1"><%= @article.title %></h2>
  <div class="box2">
   <h2 class="abst1"><%= @article.abstract %></h2>
   <% if @article.image? %>
    <div class="thumbnail">
      <%= image_tag @article.image.url %>
    </div>
   <% end %>
   <h22 class="content1">
   <%= simple_format(@paginated_content.first) %>
   </h22>
   <%= will_paginate @paginated_content %>
   <p>
   <% case %>
    <% when @article.category_id == 1 %>
     <%= link_to "#一回生向け", '/categories/1' %>
    <% when @article.category_id == 2 %>
     <%= link_to "#Sojin Voice", '/categories/2' %>
    <% else @article.category_id == 3 %>
     <%= link_to "#その他", '/categories/3' %>
    <% end %>
   </p>
   <%= link_to "edit", edit_article_path(params[:id]) %>
     <%= link_to "delete", @article, method: :delete,
                      data: {confirm: "You sure?"} %>
  </div> 
 <% else %>
  <div class="hero-unit">
  <h3>この記事は非公開です。</h3>
  </div>
 <% end %>
<% end %>