config/routes.rb
SampleApp::Application.routes.draw do
  resources :users do
   collection do
    get :tmp
   end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts
  resources :entries
  resources :comments
  resources :articles
  resources :categories
  resources :profiles
  resources :subemails
  resources :contacts
  root 'static_pages#home'
  match '/signup',   to:'users#new',              via:'get'
  match '/signin',   to:'sessions#new',           via:'get'
  match '/signout',  to:'sessions#destroy',       via:'delete'
  match '/help',     to: 'static_pages#help',     via: 'get'
  match '/bbs',      to: 'static_pages#bbs',      via: 'get'
  match '/about',    to: 'static_pages#about',    via: 'get'
  match '/mypage',   to: 'static_pages#mypage',   via: 'get'
  get 'users/token/:uuid' => 'users#token'

end

app/views/shared/_articles_item.html.erb
<li id="<%= articles_item.id %>">
 <% if articles_item.koukai == 0 %>
  <span class="content">[下書き]</span>
 <% end %>
 <span class="content"><%= articles_item.title %></span>
 <span class="content"><%= articles_item.abstract %></span>
 <%= link_to "続きを読む", articles_item %></span>
    <% case %>
    <% when articles_item.category_id == 1 %>
     <%= link_to "#一回生向け", '/categories/1' %>
    <% when articles_item.category_id == 2 %>
     <%= link_to "#Sojin Voice", '/categories/2' %>
    <% else articles_item.category_id == 3 %>
     <%= link_to "#その他", '/categories/3' %>
    <% end %>
  <span class="timestamp">
  Posted <%= time_ago_in_words(articles_item.created_at) %> ago.
  </span>
</li>

app/views/shared/_bbs.html.erb
<% if @microposts.any? %>
  <ol class="microposts">
    <%= render partial: 'shared/bbs_item', collection: @microposts %>
  </ol>
  <%= will_paginate @microposts %>
<% end %>

app/views/shared/_bbs_item.html.erb
<li id="<%= bbs_item.id %>">
  <%= link_to gravatar_for(bbs_item.user), bbs_item.user %>
  <span class="user">
    <%= link_to bbs_item.user.name, bbs_item.user %>
  </span>
  <span class="content">
  <b> <%= bbs_item.title  %> </b>
   <%= link_to "続きを読む", bbs_item  %> 
  </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(bbs_item.created_at) %> ago.
  </span>
</li>

app/views/shared/_comment_form.html.erb
<%= form_for(@comment) do |f| %>
<%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.hidden_field :micropost_id, :value => @micropost.id %>

    <%= f.text_area :content, placeholder: "Compose new comment..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_contacts_item.html.erb
<li id="<%= contacts_item.id %>">
  <% if contacts_item.user_id.present? %>
   <%= link_to gravatar_for(contacts_item.user), contacts_item.user %>
   <span class="user">
    <%= link_to contacts_item.user.name, contacts_item.user %>
    <%= contacts_item.name if contacts_item.name.present? %>
   </span>
  <% else %> 
   <span class="user">
    <% if contacts_item.name.present? %>
     <%= contacts_item.name %>
    <% else %>   
     非ログインユーザー
    <% end %>
　 </span> 
  <% end %>
   <span class="content">
    <%= contacts_item.content %>
   </span>
   <span class="timestamp">
    Posted <%= time_ago_in_words(contacts_item.created_at) %> ago.
   </span>
</li>

app/views/shared/_entry_edit_form.html.erb
<%= form_for(@entries.find_by(user_id: current_user.id)) do |f| %>
<%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.hidden_field :micropost_id, :value => @micropost.id %>
    <%= f.select :option, [['参加', 0], ['興味あり', 1], ['参加できない', 2]] %>
  </div>
  <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_entry_form.html.erb
<%= form_for(@entry) do |f| %>
<%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.hidden_field :micropost_id, :value => @micropost.id %>    
    <%= f.select :option, [['参加', 0], ['興味あり', 1], ['参加できない', 2]] %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  <span class="user">
    <%= link_to feed_item.user.name, feed_item.user %>
  </span>
  <span class="content"><%= link_to feed_item.title, feed_item %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
  </span>
</li>

app/views/shared/_message_form.html.erb
<%= form_for(@message) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.hidden_field :receiver_id, :value => @receiver.id %>
    <%= f.text_area :content, placeholder: "Compose new message..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_field :title, placeholder: "Write a title..." %>
  </div>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_user_email_new.html.erb
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@sub_email) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :sub_email, "サブアドレス"  %>
      <%= f.text_field :sub_email %>

      <%= f.label :inform, '通知(新着記事・BBSへの投稿)'  %>
      <%= f.select :inform,
           [['京大アカウントに通知', 1],
            ['サブアドレスに通知', 2],
            ['通知しない', 3 ]]  %>

      <%= f.submit "登録", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/shared/_user_password_edit.html.erb
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      Email:<%= @user.email %> 
 
      <%= f.label :name %>
      <%= f.text_field :name %>
   
      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/shared/_user_profile.html.erb
<div class="note">
<div class="ttl"><h1>公開プロフィール</h1></div>
 <p>名前： <%= @user.name %></p>
 <% if @user.profile.nil? %> 
  <p>身分(回生・教員等):</p>
  <p>学系:</p>
  <p>自己紹介：</p>
  <p>
  <% if current_user?(@user) %>
   <%= link_to "create", new_profile_path %>
  <% end %></p>
 <% else %>
  <p>身分(回生・教員等)： <%= @profile.shozoku if @profile.shozoku.present? %></p>
  <p>学系：<%= @profile.gakukei if @profile.gakukei.present? %></p>
  <p>自己紹介：<%= @profile.self_intro if  @profile.self_intro.present? %></p>
  <p>
  <% if current_user?(@user) %>
    <%= link_to "edit", edit_profile_path(id: @user.profile) %>
  <% end %></p>
 <% end %>
</div>