config/routes.rb
SampleApp::Application.routes.draw do
  resources :users do
   collection do
    get :tmp
   end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts
  resources :entries
  resources :comments
  resources :articles
  resources :categories
  resources :profiles
  resources :subemails
  resources :contacts
  root 'static_pages#home'
  match '/signup',   to:'users#new',              via:'get'
  match '/signin',   to:'sessions#new',           via:'get'
  match '/signout',  to:'sessions#destroy',       via:'delete'
  match '/help',     to: 'static_pages#help',     via: 'get'
  match '/bbs',      to: 'static_pages#bbs',      via: 'get'
  match '/about',    to: 'static_pages#about',    via: 'get'
  match '/mypage',   to: 'static_pages#mypage',   via: 'get'
  get 'users/token/:uuid' => 'users#token'

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
 has_many :entries, dependent: :destroy
 has_many :comments, dependent: :destroy
 belongs_to :user
 default_scope -> { order('created_at DESC') }
 validates :title, presence: true 
 validates :content, presence: true, length: { maximum: 1400 }
 validates :user_id, presence: true
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :signed_in_user, only: [:create, :show, :destroy]
  before_action :correct_user,   only: [:destroy]

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_url
      users = User.all
      users.each do |user|
       PostMailer.bbs_post_email(current_user, user, @micropost).deliver
      end
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end
  
  def edit
   @micropost = Micropost.find(params[:id])
  end


  def update
   @micropost = Micropost.find(params[:id])
   if @micropost.update_attributes(micropost_params)
      flash[:success] = "Micropost updated!"
      redirect_to @micropost
    else
      render 'edit' 
    end
  end

  def destroy
    @micropost.destroy
    redirect_to root_path
  end

  def show
   @micropost = Micropost.find(params[:id])
   @entry = current_user.entries.build
   @entries = @micropost.entries
   @comment = current_user.comments.build
   @comments = @micropost.comments
  end

 private

    def micropost_params
      params.require(:micropost).permit(:content, :title)
    end

    def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
    end
end

app/views/microposts/_micropost.html.erb
<li>
  <span class="content"><%= link_to micropost.title, micropost %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
  </span>
</li>

app/views/microposts/edit.html.erb
 <div class="row">
    <aside class="span8">
      <section>
        <%= render 'shared/user_info' %>
      </section>
      <section>
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
  </div>

app/views/microposts/micropost.html.erb
<%= @micropost.content %>

app/views/microposts/show.html.erb
<div class="hero-unit">
 <% user = User.find_by(id: @micropost.user_id) %>
 <%= gravatar_for user, size: 52 %>
 <%= link_to user.name, user %> 
 <h4><%= @micropost.title %></h4>
 <%= simple_format(h(@micropost.content)) %>
 <span class="timestamp">
    Posted <%= time_ago_in_words(@micropost.created_at) %> ago.
  </span>
 <p><% if current_user?(@micropost.user) %>
  <%= link_to "edit", edit_micropost_path(params[:id]) %>
  <%= link_to "delete", @micropost, method: :delete,
         data: { confirm: "You sure?" }, title: @micropost.content %>
 <% end %></p>

</div>


<div class="hero-unit">
 <div class="entries">
 <div class="entry01">
 <h4>参加(<%= @entries.where(option: 0).count %>)</h4>
 <ol class= "microposts"> 
 <% @entries.where(option: 0).each do |entry|  %>
  <li> 
  <%= gravatar_for entry.user, size: 32 %>
   <%= link_to entry.user.name, entry.user %>
   <% if current_user?(entry.user) %>
    <%= link_to "delete", entry, method: :delete, 
                     data: {confirm: "You sure?"} %>
   <% end %>
  </li>
  <% end %>
 </ol>
 </div>

 <div class="entry01">
 <h4>興味あり(<%= @entries.where(option: 1).count %>)</h4>
 <ol class= "microposts">
  <%  @entries.where(option: 1).each do |entry| %>
   <li>
   <%= gravatar_for entry.user, size: 32 %>
   <%= link_to entry.user.name, entry.user %>
   <% if current_user?(entry.user) %>
    <%= link_to "delete", entry, method: :delete,
                     data: {confirm: "You sure?"} %>
   <% end %>
   </li>
  <% end %>
 </ol>
 </div>

 <h4>参加できない(<%= @entries.where(option: 2).count %>)</h4>
 <ol class= "microposts">
 <% @entries.where(option: 2).each do |entry| %>
  <li>
  <%= gravatar_for entry.user, size: 32 %>
  <%= link_to entry.user.name, entry.user %>
  <% if current_user?(entry.user) %>
    <%= link_to "delete", entry, method: :delete,
                     data: {confirm: "You sure?"} %>
  <% end %>
 <% end %>
 </li>
 </ol> 
 </div>
</div> 

<div class="hero-unit">
 <section>
 <h4>Comments</h4>
 <ol class= "microposts">
 <% @comments.each do |comment|  %>
  <li>
  <%= gravatar_for comment.user, size: 32 %>
   <%= link_to comment.user.name, user %>
   <%= comment.content %>
   <span class="timestamp">
    Posted <%= time_ago_in_words(comment.created_at) %> ago.
   </span>
   <% if current_user?(comment.user) %>  
    <%= link_to "delete", comment, method: :delete,
                     data: {confirm: "You sure?"} %>
   <% end %>
  </li>
  <% end %>
 </ol>
  <%= gravatar_for current_user, size: 52 %>
  <%= render 'shared/comment_form' %>
 </section>
</div>

<%  if @entries.find_by(user_id: current_user.id).present? %>
  <div class="hero-unit">
  <%= gravatar_for current_user, size: 52 %>
  <%= render 'shared/entry_edit_form' %>
 </div>
<% else %>
 <div class="hero-unit">  
  <%= gravatar_for current_user, size: 52 %>
  <%= render 'shared/entry_form' %>  
 </div>
<% end %>