config/routes.rb
SampleApp::Application.routes.draw do
  resources :users do
   collection do
    get :tmp
   end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts
  resources :entries
  resources :comments
  resources :articles
  resources :categories
  resources :profiles
  resources :subemails
  resources :contacts
  root 'static_pages#home'
  match '/signup',   to:'users#new',              via:'get'
  match '/signin',   to:'sessions#new',           via:'get'
  match '/signout',  to:'sessions#destroy',       via:'delete'
  match '/help',     to: 'static_pages#help',     via: 'get'
  match '/bbs',      to: 'static_pages#bbs',      via: 'get'
  match '/about',    to: 'static_pages#about',    via: 'get'
  match '/mypage',   to: 'static_pages#mypage',   via: 'get'
  get 'users/token/:uuid' => 'users#token'

end

app/views/layouts/_footer.html.erb
<!--
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><a href="http://news.railstutorial.jp/">News</a></li>
    </ul>
  </nav>
</footer>
-->

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse2">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "SOJIN PORTAL", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle2" data-toggle="dropdown">
                Articles <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "全ての記事", articles_path %></li>
                <li class="divider"></li>
                <li><%= link_to "一回生向け", '/categories/1' %></li>
                <li><%= link_to "Sojin Voice", '/categories/2' %></li>
                <li><%= link_to "その他", '/categories/3' %></li>
              </ul>
          </li>
          <li><%= link_to "BBS", bbs_path %></li>
          <li id="fat-menu" class="dropdown">
           <a href="#" class="dropdown-toggle2" data-toggle="dropdown">
             Account <b class="caret"></b>
           </a>
          <ul class="dropdown-menu">
            <% if signed_in? %>
             <li><%= link_to "設定", edit_user_path(current_user) %></li>
             <li><%= link_to "マイページ", mypage_path %></li>
            <% else %>
             <li><%= link_to "ログイン", signin_path %></li>
            <% end %>
            <li><%= link_to "連絡・報告", new_contact_path %></li>
            <% if signed_in? %>
              <li class="divider"></li>
              <li>
              <%= link_to "Sign out", signout_path, method: "delete" %>
              </li>
            <% end %>
              </ul>
            </li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
<!--   <div class="inner-body"> -->
    <%= render 'layouts/header' %>
    <div class="container">
     <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div> 
     <% end%>
     <%= yield %>
      <%= render 'layouts/footer' %> 
      <%= debug(params) if Rails.env.development? %>
    </div>
<!--   </div> -->
  </body>
</html>